%RUN_JOINT_SCENARIOS  The "Joint Scenarios" segment of Running_code.txt.
%
% Multi-variable scenarios: each entry constrains SEVERAL variables at once via
% a .parts cell array, so the system is forced onto a path no single-variable
% shock would produce.
%   * U.S. recession, BoC eases      (activity down + rate cut)
%   * Oil boom + tightening          (terms-of-trade boom the Bank leans against)
%   * Risk-off                       (equity crash + flight-to-quality + weaker CAD)
%   * U.S. reflation                 (Fed-led inflation, Canada responds endogenously)
%   * Stagflation                    (oil up AND unemployment up -> supply-shock path)
%   * U.S. recession, no policy response (activity down, rate held -> policy counterfactual)
%
% USAGE (from the project folder)
%   >> run_joint_scenarios
% Rj is left in the workspace.

%% --- put the project (root + src/) on the MATLAB path, from any working dir ---
thisDir = fileparts(mfilename('fullpath'));
addpath(thisDir); addpath(fullfile(thisDir,'src'));
assert(exist('main_risk_scenarios','file')==2, ...
    'main_risk_scenarios.m not found under ./src -- keep this script at the project root.');

ob = scenario_config();

% origin levels (pass 1)
[L, ix, originMonth] = scenarioOrigin(ob);

% two years of history before the origin, bands + figures on
ov = datevec(originMonth);
ob.figStart = [ov(1)-2, ov(2)];
ob.bands    = true;
ob.figures  = true;
ob.bandOpts = struct('nDraws', 400);
ob.figSub   = 'joint_scenarios';

oj = ob;
oj.scenarios = { ...
  % counterpart to "no policy response": recession WITH easing
  struct('name','U.S. recession, BoC eases', 'parts',{{ ...
     struct('var','usip','type','replay','from',[2008 1],'months',24), ...
     struct('var','rate','type','ramp','to',max(L(ix.rate)-2.0, 0.25),'months',6) }}), ...
  % terms-of-trade boom the Bank leans against
  struct('name','Oil boom + tightening', 'parts',{{ ...
     struct('var','oil', 'type','ramp','to',round(1.40*L(ix.oil)),'months',6), ...
     struct('var','rate','type','policy','step',0.25,'peak',L(ix.rate)+1.0,'hold',12,'floor',L(ix.rate)) }}), ...
  % global risk-off: equity crash, flight-to-quality yields, weaker CAD
  struct('name','Risk-off', 'parts',{{ ...
     struct('var','tsx', 'type','replay','from',[2008 9],'months',12), ...
     struct('var','long','type','ramp','to',max(L(ix.long)-1.0, 0.25),'months',3), ...
     struct('var','fx',  'type','ramp','to',1.45,'months',3) }}), ...
  % imported inflation, Fed-led -- Canada responds endogenously
  struct('name','U.S. reflation', 'parts',{{ ...
     struct('var','uscpi', 'type','replay','from',[2021 4],'months',18), ...
     struct('var','usrate','type','ramp','to',L(ix.usrate)+2.0,'months',9) }}), ...
  % stagflation: oil up and unemployment up together -> supply-shock path
  struct('name','Stagflation', 'parts',{{ ...
     struct('var','oil',  'type','ramp','to',110,'months',6), ...
     struct('var','unemp','type','hold','at',8.0) }}), ...
  % U.S. recession with the rate held fixed -- the "no policy response" counterfactual
  struct('name','U.S. recession, no policy response', 'parts',{{ ...
     struct('var','usip','type','replay','from',[2008 1],'months',24), ...
     struct('var','rate','type','hold') }}) };

Rj = main_risk_scenarios('fred', oj);
fprintf('run_joint_scenarios: done. Rj is in the workspace.\n');
